"""Pure-string renderers for the generated React project files.

These functions take validated data and return file contents. They never touch
the filesystem — keeping them pure makes them easy to unit-test.
"""

from __future__ import annotations

import json
from collections.abc import Iterable  # noqa: TC003

from appio_shared.schemas import (  # noqa: TC001
    AppSpec,
    BooleanProp,
    Component,
    NumberProp,
    Page,
    StringListProp,
    StringProp,
)

__all__ = [
    "render_app_tsx",
    "render_component_tsx",
    "render_index_html",
    "render_manifest_json",
    "render_package_json",
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _js_identifier(name: str) -> str:
    """Sanitise a string into a valid JS identifier (caller has already
    validated PascalCase / camelCase via Pydantic)."""
    return "".join(c for c in name if c.isalnum() or c == "_") or "Component"


def _props_literal(props: list[object]) -> str:
    """Render a list of PropEntry items as a JS object literal.

    The runtime component sees ``props`` as a plain object (e.g.
    ``{groupBy: "date", showTrend: true}``) regardless of how the spec
    encoded the typed key/value list.
    """
    if not props:
        return "{}"
    obj: dict[str, object] = {}
    for p in props:
        if isinstance(p, (StringProp, NumberProp, BooleanProp, StringListProp)):
            obj[p.key] = p.value
    return json.dumps(obj, ensure_ascii=False, separators=(", ", ": "))


def _route_to_segment(route: str) -> str:
    if route == "/":
        return "home"
    return route.strip("/").replace("/", "-").replace("-", "_") or "home"


def _unique_component_types(spec: AppSpec) -> list[str]:
    seen: list[str] = []
    seen_set: set[str] = set()
    for page in spec.pages:
        for comp in page.components:
            if comp.type not in seen_set:
                seen.append(comp.type)
                seen_set.add(comp.type)
    return seen


# ---------------------------------------------------------------------------
# index.html
# ---------------------------------------------------------------------------


def render_index_html(template_html: str, spec: AppSpec) -> str:
    """Substitute placeholders in the base template's ``index.html``.

    Substitutes app name + theme colors only. The ``{{ENTRY_JS}}`` and
    ``{{ENTRY_CSS}}`` placeholders are deliberately left in place — they
    are filled in by the esbuild post-build step in ``esbuild.config.mjs``
    once the hashed bundle filenames are known.
    """
    theme = spec.theme
    replacements = {
        "{{APP_NAME}}": spec.name,
        "{{THEME_COLOR}}": theme.primary,
        "{{PRIMARY_COLOR}}": theme.primary,
        "{{PRIMARY_LIGHT_COLOR}}": theme.primary_light,
        "{{BACKGROUND_COLOR}}": theme.background,
        "{{SURFACE_COLOR}}": theme.surface,
        "{{TEXT_PRIMARY_COLOR}}": theme.text_primary,
        "{{TEXT_SECONDARY_COLOR}}": theme.text_secondary,
    }
    out = template_html
    for needle, value in replacements.items():
        out = out.replace(needle, value)
    return out


# ---------------------------------------------------------------------------
# manifest.json
# ---------------------------------------------------------------------------


def render_manifest_json(template_manifest: str, spec: AppSpec) -> str:
    raw = json.loads(template_manifest)
    raw["name"] = spec.name
    raw["short_name"] = spec.name[:12]
    raw["description"] = (
        raw.get("description") or f"{spec.name} — built with Appio"
    ).replace("{{APP_DESCRIPTION}}", f"{spec.name} — built with Appio")
    raw["background_color"] = spec.theme.background
    raw["theme_color"] = spec.theme.primary
    return json.dumps(raw, indent=2) + "\n"


# ---------------------------------------------------------------------------
# package.json — preserved verbatim from base template
# ---------------------------------------------------------------------------


def render_package_json(template_package: str, spec: AppSpec) -> str:
    raw = json.loads(template_package)
    raw["name"] = (
        "".join(c.lower() if c.isalnum() else "-" for c in spec.name).strip("-")
        or "appio-pwa"
    )
    raw["description"] = f"{spec.name} — built with Appio"
    return json.dumps(raw, indent=2) + "\n"


# ---------------------------------------------------------------------------
# Component file (one .tsx per unique component type used in the spec)
# ---------------------------------------------------------------------------


# localStorage templates: agent JSX references Stores.useXxxStore.
_COMPONENT_HEADER_LOCAL = """\
// AUTO-GENERATED by appio_codegen — do not edit by hand.
// @ts-nocheck
/* eslint-disable */
import React, { useState, useEffect, useMemo } from "react";
import * as Stores from "../stores";
"""

# Convex templates: agent JSX references api.<domain>.<fn> + useQuery / useMutation
# directly. The `api` import path is relative to src/components/Foo.tsx →
# ../../convex/_generated/api. `useCollection` from @appio/ui/hooks is also
# surfaced because the agent's system prompt (T3.3) shows it as the primary
# data-access pattern.
_COMPONENT_HEADER_CONVEX = """\
// AUTO-GENERATED by appio_codegen — do not edit by hand.
// @ts-nocheck
/* eslint-disable */
import React, { useState, useEffect, useMemo } from "react";
import { useQuery, useMutation } from "convex/react";
import { useCollection } from "@appio/ui/hooks";
import { api } from "../../convex/_generated/api";
"""


def render_component_tsx(
    component_type: str,
    instances: Iterable[Component],
    *,
    storage_backend: str = "localStorage",
) -> str:
    """Render a component file.

    If any instance of this component type carries a JSX body, that body wins
    (the first one is used). Otherwise the component renders a labelled
    placeholder. Props from the *first* instance are exposed as a const so the
    JSX body can reference ``props.foo`` directly.

    The generated file uses ``// @ts-nocheck`` because the AI-supplied JSX
    body is opaque to the TypeScript checker — it may reference store hooks
    or Convex `api.*` refs or props in ways the type system can't statically
    prove. The build step (esbuild) will still report any actual syntax
    errors via the AutoFix loop.

    ``storage_backend`` selects the import header:
    - "localStorage" → ``import * as Stores from "../stores";``
    - "convex"       → ``import { api } from "../../convex/_generated/api";``
                       ``import { useQuery, useMutation } from "convex/react";``
    """
    instances_list = list(instances)
    first = instances_list[0]
    jsx_body = first.jsx
    props_literal = _props_literal(list(first.props))
    name = _js_identifier(component_type)
    name_literal = json.dumps(name)

    if jsx_body and jsx_body.strip():
        body = jsx_body.strip()
        # The JSX body is allowed to be either a single root element or
        # multiple lines; wrap it in a fragment to be safe.
        if not body.startswith("<"):
            body = f"<>{body}</>"
    else:
        body = (
            f'<div className="p-4 text-text-secondary">'
            f"{{/* Placeholder for {name} */}}"
            f"{{{name_literal}}}"
            f"</div>"
        )

    if storage_backend == "convex":
        header = _COMPONENT_HEADER_CONVEX
        data_binding = (
            "// @ts-ignore — api is a Convex codegen artifact; shape is opaque\n"
            "const _api = api;\n"
        )
    else:
        header = _COMPONENT_HEADER_LOCAL
        data_binding = (
            "// @ts-ignore — Stores barrel may be empty for some templates\n"
            "const _stores = Stores;\n"
        )

    return (
        f"{header}\n"
        f"const props = {props_literal};\n"
        f"{data_binding}\n"
        f"export default function {name}() {{\n"
        f"  return (\n"
        f"    {body}\n"
        f"  );\n"
        f"}}\n"
    )


# ---------------------------------------------------------------------------
# App.tsx — routes pages, mounts a tab bar if any page uses ``layout: tabs``
# ---------------------------------------------------------------------------


_APP_HEADER = """\
// AUTO-GENERATED by appio_codegen — do not edit by hand.
import React, { useState } from "react";
"""


def _component_import(name: str) -> str:
    return f'import {name} from "./components/{name}";\n'


def _page_jsx(page: Page) -> str:
    """Render the JSX for a single page (a column of components)."""
    items: list[str] = []
    for idx, comp in enumerate(page.components):
        items.append(f'        <{comp.type} key="{idx}" />')
    body = "\n".join(items) if items else "        <div />"
    title = page.title or page.route
    title_literal = json.dumps(title, ensure_ascii=False)
    segment = _route_to_segment(page.route)
    return (
        f'    <section id="page-{segment}" '
        f'className="flex flex-col gap-4 p-4">\n'
        f'      <header className="text-lg font-semibold">{{{title_literal}}}</header>\n'
        f'      <div className="flex flex-col gap-3">\n'
        f"{body}\n"
        f"      </div>\n"
        f"    </section>"
    )


_TAB_ICONS = ["🏠", "📋", "📊", "⚙️", "✨"]


def render_app_tsx(spec: AppSpec) -> str:
    """Render the top-level ``src/App.tsx`` file."""
    component_types = _unique_component_types(spec)
    imports = "".join(_component_import(name) for name in component_types)

    has_tabs = any(p.layout == "tabs" for p in spec.pages)
    routes = [p.route for p in spec.pages]

    page_blocks = []
    for page in spec.pages:
        route_literal = json.dumps(page.route)
        page_blocks.append(
            f"    [{route_literal}]: (\n"
            f"{_page_jsx(page)}\n"
            f"    ),"
        )
    pages_record = "\n".join(page_blocks)

    if has_tabs:
        tab_buttons = []
        for idx, page in enumerate(spec.pages):
            label = page.title or page.route.strip("/") or "Home"
            label_literal = json.dumps(label, ensure_ascii=False)
            icon_literal = json.dumps(
                _TAB_ICONS[idx % len(_TAB_ICONS)], ensure_ascii=False
            )
            route_literal = json.dumps(page.route)
            tab_buttons.append(
                f"        <button\n"
                f"          key={route_literal}\n"
                f'          type="button"\n'
                f"          onClick={{() => setCurrentPage({route_literal})}}\n"
                f'          className={{`flex flex-col items-center text-xs '
                f"${{currentPage === {route_literal} "
                f'? "text-primary" : "text-text-secondary"}}`}}\n'
                f"        >\n"
                f'          <span className="text-lg mb-0.5">{{{icon_literal}}}</span>\n'
                f"          {{{label_literal}}}\n"
                f"        </button>"
            )
        nav = (
            '      <nav className="fixed bottom-0 left-0 right-0 bg-surface '
            'border-t border-gray-200 flex justify-around py-3 px-4 safe-area-pb">\n'
            + "\n".join(tab_buttons)
            + "\n      </nav>\n"
        )
    else:
        nav = ""

    initial_route = '"/"' if "/" in routes else f'"{routes[0]}"'

    return (
        f"{_APP_HEADER}{imports}\n"
        f"export default function App() {{\n"
        f"  const [currentPage, setCurrentPage] = useState<string>({initial_route});\n\n"
        f"  const pages: Record<string, React.ReactNode> = {{\n"
        f"{pages_record}\n"
        f"  }};\n\n"
        f"  return (\n"
        f'    <div className="min-h-screen bg-background text-text-primary">\n'
        f'      <main className="pb-24">{{pages[currentPage] ?? pages[{initial_route}]}}</main>\n'
        f"{nav}"
        f"    </div>\n"
        f"  );\n"
        f"}}\n"
    )
