"""Claude vision critique service for the agent feedback loop.

Takes the screenshots produced by ``screenshot.capture_app_screenshots``
and asks Claude Sonnet 4.6 to grade them against a mobile-UI checklist,
returning a structured critique the agent can act on.

The critique is requested via Anthropic's tool-use mode, which forces
Claude to return strictly schema-conformant JSON instead of free-form
text we'd have to parse heuristically.
"""

from __future__ import annotations

import base64
import logging
from dataclasses import dataclass
from typing import Any

import anthropic

from apps.api.config import settings
from apps.api.domains.generation.model_router import AgentStep, pick_model
from apps.api.domains.generation.screenshot import ScreenshotResult

log = logging.getLogger(__name__)

__all__ = ["CritiqueError", "CritiqueResult", "CritiqueIssue", "request_critique"]

_MAX_TOKENS = 2048
_TIMEOUT_S = 60.0


_CRITIQUE_SYSTEM = """\
You are a senior mobile UI designer reviewing a Progressive Web App that was \
auto-generated by another AI. The app is intended to look and feel like a \
real native iOS application — NOT a website.

You will be shown 4 screenshots of the same app at iPhone 14 Pro Max viewport \
(430×932): light/dark mode, with/without data. Grade the visual quality \
critically against this checklist:

## Critical issues (severity: high) — REPORT IF YOU SEE ANY OF THESE

- **Touching cards / zero gap** between sibling cards or list rows. If \
  multiple cards or rows are stacked vertically with no visible space \
  between them, this is HIGH severity. Fix: add `space-y-3` or \
  `space-y-4` to the parent container.
- **Inline forms instead of BottomSheet.** If you see an "Add new" or \
  "Create" form rendered permanently at the bottom of the page (instead \
  of being hidden inside a BottomSheet that opens via FAB), this is HIGH \
  severity. Fix: wrap the form in `<BottomSheet open={open} onClose=...>` \
  and trigger it from a `<FAB>`.
- **Edge-to-edge content.** Cards or content touching the absolute left/ \
  right edges of the phone (no `px-5` on main). HIGH severity.
- The app looks like a generic web page (hero sections, footers, marketing \
  layouts, side-by-side desktop layouts, oversized whitespace).
- Touch targets smaller than 44×44 px (icon buttons, taps).
- Text unreadable in dark mode (low contrast, invisible icons).
- Major layout broken (overlapping elements, FAB hidden behind tab bar, \
  content cut off, scroll trap).
- Missing or empty critical state (e.g. blank screen instead of empty state).
- Missing FAB when one is clearly needed for the "add" action.

## Polish issues (severity: medium)
- Inconsistent spacing between similar elements
- Cards/rows too tight or too loose (should breathe but not waste space)
- Subtle text contrast issues (placeholders too dim, etc.)
- Missing tap feedback hints (everything looks static)
- Inconsistent corner radii or shadows between elements

## Nice-to-have (severity: low)
- Could use better empty-state copy
- Icon weights inconsistent
- Slightly off color choices

## DO NOT report
- Tab title bar / browser chrome (out of our control)
- Cloudflare beacon CSP errors (infra)
- Things that require backend or external APIs
- Personal preferences about specific colors

For each issue you find, respond by calling the `report_critique` tool ONCE \
with a structured object. Be specific and actionable: name the component, \
describe what's wrong, and propose a concrete fix the agent can apply by \
editing the source file. Reference Tailwind classes and the component \
library (Screen, AppBar, Card, ListItem, FAB, BottomSheet, IconButton, \
Button, Input, SegmentedControl, EmptyState, TabBar, Icons).

Score the overall UI quality from 0 (broken) to 10 (App Store ready). \
A score of 8+ means it's ready to ship. A score below 8 means at least one \
fix pass is needed.
"""


_REPORT_TOOL: dict[str, Any] = {
    "name": "report_critique",
    "description": (
        "Report your critique of the app's UI quality. Call this exactly once "
        "with a complete assessment."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "overall_score": {
                "type": "number",
                "description": "Overall UI quality score from 0 to 10. 8+ = ship-ready.",
                "minimum": 0,
                "maximum": 10,
            },
            "summary": {
                "type": "string",
                "description": "One-sentence summary of the app's overall visual quality.",
            },
            "issues": {
                "type": "array",
                "description": "List of issues found, ordered by severity.",
                "items": {
                    "type": "object",
                    "properties": {
                        "severity": {
                            "type": "string",
                            "enum": ["high", "medium", "low"],
                        },
                        "screen": {
                            "type": "string",
                            "description": (
                                "Which screenshot the issue is visible in: "
                                "light-empty, light-data, dark-empty, or dark-data."
                            ),
                        },
                        "component": {
                            "type": "string",
                            "description": (
                                "Component or area where the issue is "
                                "(e.g. AppBar, TaskRow, FAB, BottomSheet)."
                            ),
                        },
                        "problem": {
                            "type": "string",
                            "description": "What specifically is wrong, in one sentence.",
                        },
                        "fix": {
                            "type": "string",
                            "description": (
                                "Concrete code change to make. Reference the "
                                "components/ui library and Tailwind v4 classes."
                            ),
                        },
                    },
                    "required": ["severity", "component", "problem", "fix"],
                },
            },
        },
        "required": ["overall_score", "summary", "issues"],
    },
}


class CritiqueError(RuntimeError):
    """Raised when the vision critique call fails."""


@dataclass(frozen=True, slots=True)
class CritiqueIssue:
    severity: str
    screen: str
    component: str
    problem: str
    fix: str


@dataclass(frozen=True, slots=True)
class CritiqueResult:
    overall_score: float
    summary: str
    issues: list[CritiqueIssue]
    input_tokens: int
    output_tokens: int
    cost_usd: float

    @property
    def has_high_severity(self) -> bool:
        return any(i.severity == "high" for i in self.issues)

    @property
    def needs_fix_pass(self) -> bool:
        """Adaptive trigger: fix pass when there are high-severity issues
        OR the overall score is below 8.

        We err on the side of running the fix pass — it costs ~$0.04
        extra and the quality improvement is dramatic for the marginal
        cases (score 7-8 typically have 1-2 fixable issues that are
        very easy to spot but make the difference between 'looks like
        a real app' and 'looks like a prototype')."""
        return self.has_high_severity or self.overall_score < 8

    def to_agent_message(self) -> str:
        """Format the critique as a follow-up user message for the agent
        loop. Only includes high+medium severity items so we don't
        overload the agent with low-priority polish notes."""
        relevant = [i for i in self.issues if i.severity in {"high", "medium"}]
        if not relevant:
            return ""

        lines = [
            "I reviewed your app via screenshots. Overall score: "
            f"{self.overall_score}/10. {self.summary}",
            "",
            "Please fix the following specific issues by editing the right "
            "source files. After fixing, run_build once and stop:",
            "",
        ]
        for i, issue in enumerate(relevant, 1):
            lines.append(
                f"{i}. [{issue.severity.upper()}] {issue.component} "
                f"({issue.screen or 'all'}): {issue.problem}"
            )
            lines.append(f"   FIX: {issue.fix}")
        lines.append("")
        lines.append(
            "Make ONLY the fixes listed above. Do not refactor anything else. "
            "After write_file calls, run_build once and stop."
        )
        return "\n".join(lines)


def _compute_cost(input_tokens: int, output_tokens: int) -> float:
    model = pick_model(AgentStep.CRITIQUE)
    return model.compute_cost(input_tokens, output_tokens)


def _build_image_blocks(screenshots: list[ScreenshotResult]) -> list[dict[str, Any]]:
    """Convert screenshots to Anthropic image content blocks with labels."""
    blocks: list[dict[str, Any]] = []
    for shot in screenshots:
        encoded = base64.standard_b64encode(shot.png_bytes).decode("ascii")
        blocks.append(
            {
                "type": "text",
                "text": f"Screenshot: {shot.label}",
            }
        )
        blocks.append(
            {
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": "image/png",
                    "data": encoded,
                },
            }
        )
    return blocks


async def request_critique(
    screenshots: list[ScreenshotResult],
) -> CritiqueResult:
    """Send screenshots to Claude vision and parse the structured critique."""
    if not screenshots:
        raise CritiqueError("no screenshots provided")

    client = anthropic.AsyncAnthropic(
        api_key=settings.anthropic_api_key,
        timeout=_TIMEOUT_S,
    )

    image_blocks = _build_image_blocks(screenshots)
    image_blocks.append(
        {
            "type": "text",
            "text": (
                "Review these 4 screenshots of the auto-generated app and "
                "report your critique by calling the report_critique tool. "
                "Be specific and actionable. Score 0-10 based on whether "
                "this looks like a real mobile app."
            ),
        }
    )

    critique_model = pick_model(AgentStep.CRITIQUE)
    log.info("critique_model_selected", model=critique_model.model_id)

    try:
        response = await client.messages.create(
            model=critique_model.model_id,
            max_tokens=_MAX_TOKENS,
            system=[
                {
                    "type": "text",
                    "text": _CRITIQUE_SYSTEM,
                    "cache_control": {"type": "ephemeral"},
                }
            ],
            tools=[_REPORT_TOOL],
            tool_choice={"type": "tool", "name": "report_critique"},
            messages=[{"role": "user", "content": image_blocks}],
        )
    except anthropic.APIError as exc:
        raise CritiqueError(f"vision API error: {exc}") from exc
    except Exception as exc:
        raise CritiqueError(f"vision call failed: {exc}") from exc

    # Find the tool_use block with our report
    tool_block = next(
        (b for b in response.content if b.type == "tool_use" and b.name == "report_critique"),
        None,
    )
    if tool_block is None:
        raise CritiqueError("Claude did not call report_critique tool")

    payload = tool_block.input
    try:
        issues = [
            CritiqueIssue(
                severity=str(i.get("severity", "low")),
                screen=str(i.get("screen", "")),
                component=str(i.get("component", "")),
                problem=str(i.get("problem", "")),
                fix=str(i.get("fix", "")),
            )
            for i in payload.get("issues", [])
        ]
    except Exception as exc:
        raise CritiqueError(f"malformed critique payload: {exc}") from exc

    input_tokens = response.usage.input_tokens
    output_tokens = response.usage.output_tokens
    cost = _compute_cost(input_tokens, output_tokens)

    return CritiqueResult(
        overall_score=float(payload.get("overall_score", 5.0)),
        summary=str(payload.get("summary", "")),
        issues=issues,
        input_tokens=input_tokens,
        output_tokens=output_tokens,
        cost_usd=cost,
    )
