import { build } from "esbuild";
import { readFileSync, writeFileSync, readdirSync, statSync, copyFileSync } from "fs";
import { join, extname, resolve, dirname } from "path";

// Resolve base directory (where this config lives)
const baseDir = dirname(new URL(import.meta.url).pathname);
const outdir = "dist";

// PostCSS + Tailwind v4 plugin for esbuild
const tailwindPlugin = {
  name: "tailwind-postcss",
  setup(build) {
    build.onLoad({ filter: /\.css$/ }, async (args) => {
      const postcss = (await import("postcss")).default;
      const tailwindcss = (await import("@tailwindcss/postcss")).default;
      const css = readFileSync(args.path, "utf8");
      const result = await postcss([tailwindcss()]).process(css, {
        from: args.path,
      });
      return { contents: result.css, loader: "css" };
    });
  },
};

const result = await build({
  entryPoints: ["src/index.tsx"],
  bundle: true,
  outdir,
  format: "esm",
  splitting: true,
  minify: true,
  sourcemap: false,
  target: ["es2020"],
  jsx: "automatic",
  jsxImportSource: "react",
  loader: {
    ".tsx": "tsx",
    ".ts": "ts",
    ".jsx": "jsx",
    ".js": "js",
    ".svg": "dataurl",
    ".png": "dataurl",
    ".webp": "dataurl",
  },
  plugins: [tailwindPlugin],
  define: {
    "process.env.NODE_ENV": '"production"',
  },
  entryNames: "[name]-[hash]",
  chunkNames: "chunks/[name]-[hash]",
  assetNames: "assets/[name]-[hash]",
  metafile: true,
});

// --- Post-build: inject hashed filenames into index.html ---

// Find the entry JS and CSS files from the metafile
const outputs = result.metafile.outputs;
let entryJs = "";
let entryCss = "";

for (const [outPath, meta] of Object.entries(outputs)) {
  const relativePath = outPath.replace(`${outdir}/`, "");
  if (meta.entryPoint === "src/index.tsx") {
    entryJs = `/${relativePath}`;
  }
  if (relativePath.endsWith(".css") && !relativePath.includes("chunks/")) {
    entryCss = `/${relativePath}`;
  }
}

// Read index.html template and inject paths
const htmlTemplatePath = join(baseDir, "index.html");
let html = readFileSync(htmlTemplatePath, "utf8");
html = html.replace("{{ENTRY_JS}}", entryJs);
if (entryCss) {
  html = html.replace("<!-- {{ENTRY_CSS}} -->", `<link rel="stylesheet" href="${entryCss}" />`);
} else {
  html = html.replace("<!-- {{ENTRY_CSS}} -->", "");
}
writeFileSync(join(outdir, "index.html"), html);

// --- Copy manifest.json if present ---
try {
  copyFileSync("manifest.json", join(outdir, "manifest.json"));
} catch {
  // manifest.json is generated by the code generator, may not exist yet
}

// --- Copy gate.js (install landing served pre-install) ---
// Served as /gate.js so the strict CSP `script-src 'self'` allows it
// without needing unsafe-inline. The hashed React bundle URL is injected
// via the <script data-entry="..."> attribute at build time.
copyFileSync(join(baseDir, "gate.js"), join(outdir, "gate.js"));

// --- Generate precache manifest from dist/ ---
function collectFiles(dir, base = "") {
  const files = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const rel = base ? `${base}/${entry}` : entry;
    if (statSync(full).isDirectory()) {
      files.push(...collectFiles(full, rel));
    } else {
      files.push(`/${rel}`);
    }
  }
  return files;
}

const precacheFiles = collectFiles(outdir);

// Read sw.js from the base template directory (not cwd)
const swTemplatePath = join(baseDir, "sw.js");
const swTemplate = readFileSync(swTemplatePath, "utf8");
const swOutput = swTemplate.replace(
  '"__PRECACHE_MANIFEST__"',
  JSON.stringify(precacheFiles)
);
writeFileSync(join(outdir, "sw.js"), swOutput);

console.log(`Build complete: ${precacheFiles.length} files`);
