import type { Persona } from "../types.js";

export const brutalistBold: Persona = {
  id: "brutalist-bold",
  name: "Brutalist Bold",
  description:
    "Pure black-and-white surfaces with thick borders, zero radius, and no drop shadows. Weight carries the hierarchy; whitespace does the separating.",
  inspiration: "Vercel docs — sharp edges, high-contrast type, shadow-free composition.",
  light: {
    oklch: {
      background: "oklch(1 0 0)",
      foreground: "oklch(0 0 0)",
      card: "oklch(1 0 0)",
      cardForeground: "oklch(0 0 0)",
      primary: "oklch(0 0 0)",
      primaryForeground: "oklch(1 0 0)",
      secondary: "oklch(0.967 0.001 286.375)",
      secondaryForeground: "oklch(0 0 0)",
      muted: "oklch(0.967 0.001 286.375)",
      mutedForeground: "oklch(0.274 0.006 286.033)",
      accent: "oklch(0.967 0.001 286.375)",
      accentForeground: "oklch(0 0 0)",
      border: "oklch(0 0 0)",
      input: "oklch(0 0 0)",
      ring: "oklch(0 0 0)",
      destructive: "oklch(0.577 0.245 27.325)",
      destructiveForeground: "oklch(1 0 0)",
    },
    rgb: {
      background: "#ffffff",
      foreground: "#000000",
      card: "#ffffff",
      cardForeground: "#000000",
      primary: "#000000",
      primaryForeground: "#ffffff",
      secondary: "#f4f4f5",
      secondaryForeground: "#000000",
      muted: "#f4f4f5",
      mutedForeground: "#27272a",
      accent: "#f4f4f5",
      accentForeground: "#000000",
      border: "#000000",
      input: "#000000",
      ring: "#000000",
      destructive: "#e7000b",
      destructiveForeground: "#ffffff",
    },
  },
  dark: {
    oklch: {
      background: "oklch(0 0 0)",
      foreground: "oklch(1 0 0)",
      card: "oklch(0 0 0)",
      cardForeground: "oklch(1 0 0)",
      primary: "oklch(1 0 0)",
      primaryForeground: "oklch(0 0 0)",
      secondary: "oklch(0.274 0.006 286.033)",
      secondaryForeground: "oklch(1 0 0)",
      muted: "oklch(0.274 0.006 286.033)",
      mutedForeground: "oklch(0.871 0.006 286.286)",
      accent: "oklch(0.274 0.006 286.033)",
      accentForeground: "oklch(1 0 0)",
      border: "oklch(1 0 0)",
      input: "oklch(1 0 0)",
      ring: "oklch(1 0 0)",
      destructive: "oklch(0.637 0.237 25.331)",
      destructiveForeground: "oklch(0 0 0)",
    },
    rgb: {
      background: "#000000",
      foreground: "#ffffff",
      card: "#000000",
      cardForeground: "#ffffff",
      primary: "#ffffff",
      primaryForeground: "#000000",
      secondary: "#27272a",
      secondaryForeground: "#ffffff",
      muted: "#27272a",
      mutedForeground: "#d4d4d8",
      accent: "#27272a",
      accentForeground: "#ffffff",
      border: "#ffffff",
      input: "#ffffff",
      ring: "#ffffff",
      destructive: "#fb2c36",
      destructiveForeground: "#000000",
    },
  },
  typography: {
    heading: {
      family: "'Space Grotesk', 'Inter', ui-sans-serif, system-ui, sans-serif",
      weight: 900,
      lineHeight: 1,
      letterSpacing: "-0.04em",
    },
    body: {
      family: "'Inter', ui-sans-serif, system-ui, -apple-system, sans-serif",
      weight: 500,
      lineHeight: 1.45,
      letterSpacing: "-0.01em",
    },
    mono: {
      family: "'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    },
    scale: {
      display: 4.5,
      h1: 3.25,
      h2: 2.25,
      h3: 1.5,
      body: 1,
      small: 0.875,
    },
  },
  shape: {
    radius: { none: 0, sm: 0, md: 0, lg: 0, xl: 0, full: 0 },
    shadow: {
      none: "none",
      sm: "none",
      md: "none",
      lg: "none",
      xl: "none",
    },
    border: { thin: 2, medium: 3, thick: 4 },
  },
  motion: {
    duration: { instant: 0, fast: 80, medium: 140, slow: 200, slower: 280 },
    ease: {
      standard: "linear",
      out: "cubic-bezier(0, 0, 0.2, 1)",
      in: "cubic-bezier(0.4, 0, 1, 1)",
      emphasized: "steps(4, end)",
      spring: "cubic-bezier(0.5, 0, 0.5, 1)",
    },
  },
};
